language: node_js
node_js:
 - "0.10"
 - "0.8"
services:
 - redis
before_install:
 - "npm install -g grunt-cli coffee-script"
install:
 - "npm install"
script:
 - "npm test"
branches:
  only:
    - "master"
notifications:
  hipchat:
    secure: "ifjLqKZGg0dN8acCjcov0IeW+2ob8zg6K5N1fh8YitJOGjOe1BhRBKe+6xT2yyvu+dYl+MrfL3BaXLjUzXe2R7gxTCc+vvBrBaJiyiSd0xBk0ZCG2XopxmvT5dgvdA+kgysVuDNYiewIFyojn3kY7kIM0T+NMfN83RJed7sfDEE="
